import { Roboto, Roboto_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

// 1. Importer fontene med "variable" property
const robotoSans = Roboto({
    variable: "--font-roboto-sans",
    subsets: ["latin"],
    weight: ["400", "700"], // legg til ønskede vekter!
});

const robotoMono = Roboto_Mono({
    variable: "--font-roboto-mono",
    subsets: ["latin"],
    weight: ["400", "700"], // legg til ønskede vekter!
});

export const metadata = {
    title: "Next Topics",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="no" className={`${robotoSans.variable} ${robotoMono.variable}`}>
        <body
          className={`${robotoSans.className} min-h-screen flex flex-col bg-background text-foreground antialiased`}
        >
          <Header />
          <main className="grow mx-auto max-w-5xl px-4 py-8">{children}</main>
          <Footer />
        </body>
      </html>
    );
}

