import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang='no'>
            <body className='min-h-screen flex flex-col bg-background text-foreground antialiased'>
                <Header />
                <main className='grow mx-auto max-w-5xl px-4 py-8'>
                    {children}
                </main>
                <Footer />
            </body>
        </html>
    );
}
